"""epic 3 story 3.10: prompt_version table

Revision ID: 0934d97cc44f
Revises: dafa1cbb0d49
Create Date: 2026-07-21 01:10:06.716636

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0934d97cc44f'
down_revision: str | None = 'dafa1cbb0d49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_version_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_version_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_version_created_at'))
        batch_op.drop_index(batch_op.f('ix_prompt_version_active'))

    op.drop_table('prompt_version')
    # ### end Alembic commands ###
