"""epic 5 story 5.4: trade review backoff column

Revision ID: 14ceeb145775
Revises: 459c6bc4560b
Create Date: 2026-07-22 02:03:18.071375

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '14ceeb145775'
down_revision: str | None = '459c6bc4560b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_next_attempt_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('review_next_attempt_at')

    # ### end Alembic commands ###
