"""epic 5 story 5.1: trade_review table

Revision ID: 459c6bc4560b
Revises: e06459cac8b3
Create Date: 2026-07-21 23:30:51.307135

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '459c6bc4560b'
down_revision: str | None = 'e06459cac8b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('why_entered', sa.Text(), nullable=False),
    sa.Column('supporting_info', sa.JSON(), nullable=False),
    sa.Column('risks_at_entry', sa.JSON(), nullable=False),
    sa.Column('reasoning_correct', sa.Boolean(), nullable=True),
    sa.Column('what_worked', sa.JSON(), nullable=False),
    sa.Column('misleading_signals', sa.JSON(), nullable=False),
    sa.Column('hindsight_view', sa.Text(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('confidence_calibration', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_review_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_review_trade_id'), ['trade_id'], unique=False)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        # server_default backfills existing rows (an upgrade on a live Pi DB
        # already has closed trades) so the NOT NULL add succeeds; matches
        # the Python-side mapped_column defaults in clav.data.tables.
        batch_op.add_column(
            sa.Column(
                'review_status', sa.String(length=8), nullable=False, server_default='pending'
            )
        )
        batch_op.add_column(
            sa.Column('review_attempts', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_trade_review_status'), ['review_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_review_status'))
        batch_op.drop_column('review_attempts')
        batch_op.drop_column('review_status')

    with op.batch_alter_table('trade_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_review_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trade_review_created_at'))

    op.drop_table('trade_review')
    # ### end Alembic commands ###
