"""epic 4 story 4.1: health_event table

Revision ID: 91ead6156151
Revises: 104e5843d494
Create Date: 2026-07-21 06:52:41.730718

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '91ead6156151'
down_revision: str | None = '104e5843d494'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['scan_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_event_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_event_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_event_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_event_ts'))
        batch_op.drop_index(batch_op.f('ix_health_event_status'))
        batch_op.drop_index(batch_op.f('ix_health_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_health_event_category'))

    op.drop_table('health_event')
    # ### end Alembic commands ###
