"""epic 1 baseline schema

Revision ID: a84af8be7152
Revises: 
Create Date: 2026-07-09 23:50:39.421256

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a84af8be7152'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_symbol'), ['symbol'], unique=True)

    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('buying_power', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('realized_pl', sa.Float(), nullable=False),
    sa.Column('gross_exposure', sa.Float(), nullable=False),
    sa.Column('net_exposure', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('sector_allocation', sa.JSON(), nullable=False),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshot_ts'), ['ts'], unique=False)

    op.create_table('scan_cycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('market_open', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_system_control_key')
    )
    op.create_table('candle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'ts', name='uq_candle_instrument_tf_ts')
    )
    with op.batch_alter_table('candle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candle_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candle_ts'), ['ts'], unique=False)

    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('llm_signal', sa.Float(), nullable=False),
    sa.Column('portfolio_bias', sa.Float(), nullable=False),
    sa.Column('target_qty', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['scan_cycle_id'], ['scan_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_scan_cycle_id'), ['scan_cycle_id'], unique=False)

    op.create_table('indicator_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('vol_avg_20', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicator_set_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_set_ts'), ['ts'], unique=False)

    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', name='uq_position_instrument')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_order_client_order_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.Column('broker_fill_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fill_order_id'), ['order_id'], unique=False)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=False),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.Column('entry_decision_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('realized_pl', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['entry_decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['exit_order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_instrument_id'))

    op.drop_table('trade')
    with op.batch_alter_table('fill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fill_order_id'))

    op.drop_table('fill')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_instrument_id'))

    op.drop_table('order')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_instrument_id'))

    op.drop_table('position')
    with op.batch_alter_table('indicator_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicator_set_ts'))
        batch_op.drop_index(batch_op.f('ix_indicator_set_instrument_id'))

    op.drop_table('indicator_set')
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_scan_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_decision_instrument_id'))

    op.drop_table('decision')
    with op.batch_alter_table('candle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candle_ts'))
        batch_op.drop_index(batch_op.f('ix_candle_instrument_id'))

    op.drop_table('candle')
    op.drop_table('system_control')
    op.drop_table('scan_cycle')
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshot_ts'))

    op.drop_table('portfolio_snapshot')
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_symbol'))

    op.drop_table('instrument')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
