"""epic 3 story 3.7: trade_proposal decision journal

Revision ID: dafa1cbb0d49
Revises: e0139e9f3aca
Create Date: 2026-07-21 01:03:50.495789

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dafa1cbb0d49'
down_revision: str | None = 'e0139e9f3aca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('proposed_qty', sa.Integer(), nullable=False),
    sa.Column('executed_qty', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('inputs_ref', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_proposal_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposal_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposal_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_proposal_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_trade_proposal_decision_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposal_created_at'))

    op.drop_table('trade_proposal')
    # ### end Alembic commands ###
