"""epic 3 story 3.3: news_item and social_digest tables

Revision ID: e0139e9f3aca
Revises: aff2e8f04f7e
Create Date: 2026-07-20 20:44:15.531924

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e0139e9f3aca'
down_revision: str | None = 'aff2e8f04f7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_news_item_content_hash')
    )
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_item_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_item_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_item_published_at'), ['published_at'], unique=False)

    op.create_table('social_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('qualifying_post_count', sa.Integer(), nullable=False),
    sa.Column('bull_count', sa.Integer(), nullable=False),
    sa.Column('bear_count', sa.Integer(), nullable=False),
    sa.Column('bull_bear_ratio', sa.Float(), nullable=False),
    sa.Column('mention_volume', sa.Integer(), nullable=False),
    sa.Column('baseline_volume', sa.Float(), nullable=False),
    sa.Column('volume_ratio', sa.Float(), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('top_posts', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_digest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_digest_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_digest_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_digest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_digest_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_social_digest_generated_at'))

    op.drop_table('social_digest')
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_item_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_item_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_news_item_content_hash'))

    op.drop_table('news_item')
    # ### end Alembic commands ###
