"""epic 4 story 4.4: config_snapshot table

Revision ID: e06459cac8b3
Revises: 91ead6156151
Create Date: 2026-07-21 18:40:47.913953

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e06459cac8b3'
down_revision: str | None = '91ead6156151'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('same_as_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['scan_cycle.id'], ),
    sa.ForeignKeyConstraint(['same_as_snapshot_id'], ['config_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', name='uq_config_snapshot_cycle_id')
    )
    with op.batch_alter_table('config_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_snapshot_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_snapshot_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_snapshot_cycle_id'), ['cycle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_snapshot_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_config_snapshot_created_at'))
        batch_op.drop_index(batch_op.f('ix_config_snapshot_content_hash'))

    op.drop_table('config_snapshot')
    # ### end Alembic commands ###
